// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9m8RQ3wqf1BqwfoskLrhUExNxTswi2ls',
    appId: '1:841740201857:web:6e8b853a2b12f0a9618280',
    messagingSenderId: '841740201857',
    projectId: 'casheregister',
    authDomain: 'casheregister.firebaseapp.com',
    storageBucket: 'casheregister.appspot.com',
    measurementId: 'G-ZPPTB5HZ50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBURWzltzJvLWcV_edg-xPtVJjHrWlwJDk',
    appId: '1:841740201857:android:dac58e344f3562f0618280',
    messagingSenderId: '841740201857',
    projectId: 'casheregister',
    storageBucket: 'casheregister.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBjAtWJi4kP0lq_AoooivL_1aGZSIByPY',
    appId: '1:841740201857:ios:b136d4d9218a0f42618280',
    messagingSenderId: '841740201857',
    projectId: 'casheregister',
    storageBucket: 'casheregister.appspot.com',
    iosClientId: '841740201857-n4elqeqtg3od6ealhjs5hanl9lv9d12u.apps.googleusercontent.com',
    iosBundleId: 'com.example.casheRegister',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBjAtWJi4kP0lq_AoooivL_1aGZSIByPY',
    appId: '1:841740201857:ios:d6e26db5facd499a618280',
    messagingSenderId: '841740201857',
    projectId: 'casheregister',
    storageBucket: 'casheregister.appspot.com',
    iosClientId: '841740201857-e9fom23ntaur5vsvm0pnp69pen1bq0tp.apps.googleusercontent.com',
    iosBundleId: 'com.example.casheRegister.RunnerTests',
  );
}
